// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApm_LZJEfCABLB7edbQQFXRpafSkwVXtc',
    appId: '1:1063142041578:web:2edfb498e744d279453493',
    messagingSenderId: '1063142041578',
    projectId: 'flutterauth-772d9',
    authDomain: 'flutterauth-772d9.firebaseapp.com',
    storageBucket: 'flutterauth-772d9.appspot.com',
    measurementId: 'G-GN61QF35VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8Tax_oIqEvy5m0qDXQd9UYqVJNyxzv8',
    appId: '1:1063142041578:android:823d9e0bb44157c3453493',
    messagingSenderId: '1063142041578',
    projectId: 'flutterauth-772d9',
    storageBucket: 'flutterauth-772d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASTrsGewIE2-6W6fIlMWKg1O43PB12B9s',
    appId: '1:1063142041578:ios:e6199c54c69a8b0d453493',
    messagingSenderId: '1063142041578',
    projectId: 'flutterauth-772d9',
    storageBucket: 'flutterauth-772d9.appspot.com',
    iosBundleId: 'com.example.fix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASTrsGewIE2-6W6fIlMWKg1O43PB12B9s',
    appId: '1:1063142041578:ios:be88b78e0933ac24453493',
    messagingSenderId: '1063142041578',
    projectId: 'flutterauth-772d9',
    storageBucket: 'flutterauth-772d9.appspot.com',
    iosBundleId: 'com.example.fix.RunnerTests',
  );
}
